services:
  - type: web
    name: pareja-api
    runtime: node
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "22"
      - key: API_BASE_URL
        value: "https://pareja-f7jx.onrender.com"
      - key: APP_DOWNLOAD_URL
        value: "https://expo.dev/@elisum94/pareja-neon"
      - key: APP_LINK_BASE
        value: "https://expo.dev/@elisum94/pareja-neon/--/"
